import {
  OrgProfile,
  SejarahItem,
  VisiMisi,
  PengurusItem,
  ProgramKerjaItem,
  KegiatanItem,
  BeritaItem,
  PrestasiItem,
  GaleriItem,
  KalenderItem,
  LayananItem,
  PendaftaranItem,
  AspirasiItem,
  SocialMediaLinks,
  SiteSettings,
} from './types';

export const initialProfile: OrgProfile = {
  nama: 'PGRI Cabang Kecamatan Pasirwangi',
  tingkat: 'Cabang (Tingkat Kecamatan)',
  kecamatan: 'Pasirwangi',
  kabupaten: 'Garut',
  provinsi: 'Jawa Barat',
  alamatSekretariat: 'Jl. Raya Pasirwangi No. 12, Pasirwangi, Garut, Jawa Barat 44161',
  email: 'pgri.pasirwangi.garut@gmail.com',
  nomorKontak: '+62 812-2345-6789',
  website: 'https://pgri-pasirwangi.or.id',
  tahunBerdiri: '1962',
  logoUrl: '',
  faviconUrl: '',
  browserTitle: 'PGRI Kecamatan Pasirwangi | Portal Informasi Digital',
  sambutanKetua: {
    nama: 'H. Ahmad Sobari, S.Pd., M.M.Pd.',
    gelar: 'S.Pd., M.M.Pd.',
    nip: '197105141995031002',
    jabatan: 'Ketua PGRI Cabang Kecamatan Pasirwangi',
    periode: 'Masa Bakti 2025 - 2030',
    fotoUrl: '/images/ketua_pgri.jpg',
    pesan:
      'Assalamu’alaikum Warahmatullahi Wabarakatuh, Sampurasun. Puji syukur kita panjatkan ke hadirat Allah SWT atas rahmat dan karunia-Nya sehingga Portal Informasi Digital PGRI Cabang Kecamatan Pasirwangi ini dapat hadir sebagai wadah komunikasi, transparansi, serta pelayanan prima bagi segenap guru dan tenaga kependidikan di wilayah Kecamatan Pasirwangi. Di era transformasi digital pendidikan ini, PGRI berkomitmen untuk terus mengawal marwah profesi pendidik, memperjuangkan hak dan kesejahteraan anggota, serta memacu peningkatan mutu pembelajaran anak bangsa. Mari kita satukan tekad: Bersama Guru, Membangun Pendidikan, Menguatkan Organisasi!',
    tandaTanganNama: 'H. Ahmad Sobari, S.Pd., M.M.Pd.',
  },
  statistik: {
    jumlahAnggota: 548,
    jumlahSekolah: 42,
    jumlahRanting: 12,
    programTerlaksana: 38,
    guruSertifikasi: 412,
  },
};

export const initialSejarah: SejarahItem = {
  id: 'sej-featured',
  tahun: '1962',
  judul: 'Perintisan & Pembentukan Awal PGRI Pasirwangi',
  ringkasan: 'Para guru perintis di lereng Gunung Kamojang bersepakat mendirikan wadah persatuan pendidik di tingkat onderdistrik Pasirwangi.',
  isiLengkap:
    'Sejarah berdirinya PGRI di wilayah Kecamatan Pasirwangi diawali oleh dedikasi para guru Sekolah Rakyat (SR) di kawasan Pasirwangi dan Barusari yang merasa pentingnya wadah persatuan untuk saling menguatkan pengabdian di pedesaan Garut. Melalui musyawarah kekeluargaan, dibentuklah kepengurusan perintis yang menjadi cikal bakal PGRI Cabang Pasirwangi.',
  gambarUrl: '/images/hero_pgri.jpg',
};

export const initialSejarahList: SejarahItem[] = [
  {
    id: 'sej-1',
    tahun: '1962',
    judul: 'Perintisan & Pembentukan Awal PGRI Pasirwangi',
    ringkasan: 'Para guru perintis di lereng Gunung Kamojang bersepakat mendirikan wadah persatuan pendidik di tingkat kewedanaan/kecamatan Pasirwangi.',
    isiLengkap:
      'Sejarah berdirinya PGRI di wilayah Pasirwangi diawali oleh inisiatif guru-guru Sekolah Rakyat (SR) yang merasa perlunya wadah persatuan pendidik untuk memperjuangkan pendidikan rakyat dan perlindungan profesi di kaki Gunung Kamojang Garut.',
    gambarUrl: '/images/hero_pgri.jpg',
  },
  {
    id: 'sej-2',
    tahun: '1984',
    judul: 'Konsolidasi Ranting Sekolah Dasar & Madrasah',
    ringkasan: 'Perluasan struktur ranting ke desa-desa di Pasirwangi seiring bertambahnya SD Inpres dan Madrasah Ibtidaiyah.',
    isiLengkap:
      'Pada dekade 1980-an, gerakan pemerataan pendidikan melahirkan puluhan sekolah baru di Pasirwangi. PGRI Pasirwangi secara proaktif membentuk ranting-ranting tingkat gugus/desa untuk mempermudah koordinasi guru PNS maupun sukarelawan.',
    gambarUrl: '/images/hero_pgri.jpg',
  },
  {
    id: 'sej-3',
    tahun: '2005',
    judul: 'Era Undang-Undang Guru dan Dosen',
    ringkasan: 'PGRI Pasirwangi memfasilitasi advokasi dan pendampingan sertifikasi pendidik bagi ratusan guru di wilayah Pasirwangi.',
    isiLengkap:
      'Pemberlakuan UU No. 14 Tahun 2005 tentang Guru dan Dosen disambut hangat oleh PGRI Pasirwangi dengan mendirikan posko bimbingan portofolio dan PLPG guru guna meningkatkan kualifikasi dan kesejahteraan guru lokal.',
    gambarUrl: '/images/hero_pgri.jpg',
  },
  {
    id: 'sej-4',
    tahun: '2019',
    judul: 'Pembangunan Gedung Guru & Penguatan Koperasi Guru',
    ringkasan: 'Penguatan sekretariat representatif dan pendirian Koperasi Pegawai Pendidik Pasirwangi.',
    isiLengkap:
      'Melalui iuran gotong royong dan dukungan pemangku kepentingan, PGRI Cabang Kecamatan Pasirwangi berhasil memperkokoh fasilitas sekretariat cabang dan penguatan koperasi sebagai penopang kesejahteraan finansial anggota.',
    gambarUrl: '/images/hero_pgri.jpg',
  },
  {
    id: 'sej-5',
    tahun: '2025 - Sekarang',
    judul: 'Transformasi Digital & Pelayanan Terpadu',
    ringkasan: 'Peluncuran Portal Informasi Digital, database keanggotaan real-time, dan advokasi perlindungan profesi berkelanjutan.',
    isiLengkap:
      'Di bawah kepengurusan Masa Bakti 2025-2030, PGRI Cabang Pasirwangi melangkah maju dengan platform digital modern, mempermudah akses layanan keanggotaan, penyaluran aspirasi transparan, serta penguatan kompetensi digital guru abad ke-21.',
    gambarUrl: '/images/hero_pgri.jpg',
  },
];

export const initialVisiMisi: VisiMisi = {
  visi: 'Terwujudnya PGRI Cabang Kecamatan Pasirwangi sebagai Organisasi Profesi yang Mandiri, Dinamis, Terpercaya, dan Dicintai Anggota dalam Memajukan Pendidikan yang Berkarakter di Pasirwangi.',
  misi: [
    'Meningkatkan kompetensi, integritas, dan profesionalisme guru secara berkelanjutan melalui pelatihan dan literasi digital.',
    'Memperkokoh rasa solidaritas, kegotongroyongan, dan kesetiakawanan sosial antar sesama pendidik dan tenaga kependidikan.',
    'Memperjuangkan perlindungan hukum, profesi, keselamatan kerja, serta kesejahteraan lahir batin bagi seluruh anggota.',
    'Membangun tata kelola organisasi yang transparan, akuntabel, demokratis, dan responsif terhadap aspirasi anggota.',
    'Menjalin kemitraan strategis dengan pemerintah kecamatan, dinas pendidikan, tokoh masyarakat, dan dunia usaha untuk kemajuan pendidikan Pasirwangi.',
  ],
  tujuan: [
    'Mewujudkan sistem pendataan dan keanggotaan guru yang valid dan terintegrasi secara digital.',
    'Menjamin hak-hak profesionalitas dan perlindungan hukum bagi setiap guru dalam menjalankan tugas kedinasan.',
    'Mendorong lahirnya inovasi pembelajaran berdampak di seluruh jenjang PAUD, SD, SMP, SMA/SMK di Pasirwangi.',
    'Mewujudkan kesejahteraan anggota yang merata melalui pembinaan koperasi dan program santunan sosial.',
  ],
  moto: 'Solidaritas, Pengabdian, dan Kemajuan Pendidikan Pasirwangi!',
};

export const initialPengurus: PengurusItem[] = [
  {
    id: 'peng-1',
    nama: 'H. Ahmad Sobari, S.Pd., M.M.Pd.',
    jabatan: 'Ketua Cabang',
    kategori: 'pimpinan',
    fotoUrl: '/images/ketua_pgri.jpg',
    periode: '2025 - 2030',
    nip: '197105141995031002',
    nuptk: '4534749651200032',
    unitKerja: 'SMPN 1 Pasirwangi',
    noUrut: 1,
    keteranganSingkat: 'Pendidik senior dengan komitmen tinggi pada modernisasi organisasi dan kesejahteraan guru.',
  },
  {
    id: 'peng-2',
    nama: 'Dra. Hj. Nunung Rohanah, M.Pd.',
    jabatan: 'Wakil Ketua I',
    kategori: 'pimpinan',
    fotoUrl: 'https://picsum.photos/seed/nunung_pgri/400/400',
    periode: '2025 - 2030',
    nip: '197308191998022001',
    nuptk: '7845751653300021',
    unitKerja: 'SDN Pasirwangi 1',
    noUrut: 2,
    keteranganSingkat: 'Fokus pada pembinaan jenjang pendidikan dasar dan pemberdayaan guru wanita di PGRI.',
  },
  {
    id: 'peng-3',
    nama: 'Dudi Supriadi, S.Pd., Gr.',
    jabatan: 'Wakil Ketua II',
    kategori: 'pimpinan',
    fotoUrl: 'https://picsum.photos/seed/dudi_pgri/400/400',
    periode: '2025 - 2030',
    nip: '198203112009021004',
    nuptk: '1234760662200054',
    unitKerja: 'SMKN 1 Pasirwangi',
    noUrut: 3,
    keteranganSingkat: 'Mengawal koordinasi jenjang vokasi, pemuda, dan kolaborasi dunia usaha industri.',
  },
  {
    id: 'peng-4',
    nama: 'Cecep Kurnia, S.Pd., M.Si.',
    jabatan: 'Sekretaris',
    kategori: 'sekretariat',
    fotoUrl: 'https://picsum.photos/seed/cecep_pgri/400/400',
    periode: '2025 - 2030',
    nip: '197904122006041011',
    nuptk: '3456757659200012',
    unitKerja: 'SDN Barusari 2',
    noUrut: 4,
    keteranganSingkat: 'Mengelola tata kelola persuratan, arsip organisasi, dan sistem informasi cabang.',
  },
  {
    id: 'peng-5',
    nama: 'Irma Suryani, S.Pd.I.',
    jabatan: 'Wakil Sekretaris',
    kategori: 'sekretariat',
    fotoUrl: 'https://picsum.photos/seed/irma_pgri/400/400',
    periode: '2025 - 2030',
    nip: '198711052011012015',
    nuptk: '5678765667300043',
    unitKerja: 'MTs Pasirwangi',
    noUrut: 5,
    keteranganSingkat: 'Bertanggung jawab atas administrasi keanggotaan dan hubungan lintas kementerian.',
  },
  {
    id: 'peng-6',
    nama: 'Hj. Elis Nurlina, S.Pd.SD.',
    jabatan: 'Bendahara',
    kategori: 'kebendaharaan',
    fotoUrl: 'https://picsum.photos/seed/elis_pgri/400/400',
    periode: '2025 - 2030',
    nip: '197509172002122003',
    nuptk: '9012753655300067',
    unitKerja: 'SDN Padamukti 1',
    noUrut: 6,
    keteranganSingkat: 'Mengelola keuangan organisasi dengan sistem akuntansi terbuka dan pelaporan periodik.',
  },
  {
    id: 'peng-7',
    nama: 'Agus Ramdani, S.Pd.',
    jabatan: 'Wakil Bendahara',
    kategori: 'kebendaharaan',
    fotoUrl: 'https://picsum.photos/seed/agus_pgri/400/400',
    periode: '2025 - 2030',
    nip: '198506222010011019',
    nuptk: '6789763665200088',
    unitKerja: 'SMPN 2 Pasirwangi',
    noUrut: 7,
    keteranganSingkat: 'Mendukung pengelolaan kas program kerja dan iuran anggota cabang.',
  },
  {
    id: 'peng-8',
    nama: 'Asep Saepuloh, S.H., S.Pd.',
    jabatan: 'Ketua Bidang Advokasi & Perlindungan Hukum',
    kategori: 'bidang',
    bidangNama: 'Advokasi & Hukum',
    fotoUrl: 'https://picsum.photos/seed/asep_pgri/400/400',
    periode: '2025 - 2030',
    nip: '198002152008011013',
    nuptk: '2345758660200076',
    unitKerja: 'SMPN 1 Pasirwangi',
    noUrut: 8,
    keteranganSingkat: 'Menangani konsultasi hukum pendidik, mediasi konflik, dan jaminan perlindungan guru.',
  },
  {
    id: 'peng-9',
    nama: 'Yayan Hendrayana, M.Kom.',
    jabatan: 'Ketua Bidang Komunikasi, Informasi & Publikasi Digital',
    kategori: 'bidang',
    bidangNama: 'Kominfo & Digital',
    fotoUrl: 'https://picsum.photos/seed/yayan_pgri/400/400',
    periode: '2025 - 2030',
    nip: '198901032014021003',
    nuptk: '4567767669200091',
    unitKerja: 'SMKN 1 Pasirwangi',
    noUrut: 9,
    keteranganSingkat: 'Pengembang infrastruktur portal digital, media sosial, dan dokumentasi kegiatan organisasi.',
  },
  {
    id: 'peng-10',
    nama: 'Siti Maryam, S.Pd., M.Pd.',
    jabatan: 'Ketua Bidang Pengembangan Profesi & Karir Guru',
    kategori: 'bidang',
    bidangNama: 'Profesi & Litbang',
    fotoUrl: 'https://picsum.photos/seed/maryam_pgri/400/400',
    periode: '2025 - 2030',
    nip: '198412102009032008',
    nuptk: '7890762664300055',
    unitKerja: 'SDN Barusari 1',
    noUrut: 10,
    keteranganSingkat: 'Mengorganisir seminar, pelatihan kurikulum merdeka, bimbingan karya tulis, dan seminar PTK.',
  },
  {
    id: 'peng-11',
    nama: 'Endang Sutisna, S.Pd.Jas.',
    jabatan: 'Ketua Bidang Olahraga, Seni & Budaya',
    kategori: 'bidang',
    bidangNama: 'Seni & Olahraga',
    fotoUrl: 'https://picsum.photos/seed/endang_pgri/400/400',
    periode: '2025 - 2030',
    nip: '197807242007011018',
    nuptk: '8901756658200034',
    unitKerja: 'SDN Sarimukti 1',
    noUrut: 11,
    keteranganSingkat: 'Koordinator pekan olahraga dan seni guru (PORSENI), senam sehat, dan seni tradisional Pasirwangi.',
  },
  {
    id: 'peng-12',
    nama: 'Rina Marlina, S.Pd.',
    jabatan: 'Ketua Bidang Kesejahteraan & Ketenagakerjaan',
    kategori: 'bidang',
    bidangNama: 'Kesejahteraan',
    fotoUrl: 'https://picsum.photos/seed/rina_pgri/400/400',
    periode: '2025 - 2030',
    nip: '198305082012122002',
    nuptk: '1235761663300089',
    unitKerja: 'SDN Pasirwangi 2',
    noUrut: 12,
    keteranganSingkat: 'Mengawal program santunan duka cita, bantuan bencana, dan advokasi guru honorer/PPPK.',
  },
];

export const initialProgramKerja: ProgramKerjaItem[] = [
  {
    id: 'prog-1',
    nama: 'Workshop Pemanfaatan AI & Media Interaktif Pembelajaran Guru',
    deskripsi: 'Pelatihan intensif bagi guru SD-SMP se-Kecamatan Pasirwangi dalam mengintegrasikan alat bantu pembelajaran cerdas dan media presentasi interaktif di kelas.',
    bidang: 'Profesi & Litbang',
    target: '150 Guru se-Kecamatan Pasirwangi',
    waktuPelaksanaan: 'Maret - Mei 2026',
    tahun: '2026',
    status: 'Sedang Berjalan',
    penanggungJawab: 'Siti Maryam, S.Pd., M.Pd.',
    progressPercent: 65,
    dokumentasiUrl: '/images/hero_pgri.jpg',
  },
  {
    id: 'prog-2',
    nama: 'Posko Bantuan Hukum & Advokasi Pendidik Siaga 24 Jam',
    deskripsi: 'Penyediaan konsultasi hukum gratis dan pendampingan profesi bagi anggota PGRI yang menghadapi kendala administratif maupun hukum terkait tugas keguruan.',
    bidang: 'Advokasi & Hukum',
    target: 'Seluruh Anggota PGRI Cabang Pasirwangi',
    waktuPelaksanaan: 'Sepanjang Tahun 2026',
    tahun: '2026',
    status: 'Sedang Berjalan',
    penanggungJawab: 'Asep Saepuloh, S.H., S.Pd.',
    progressPercent: 80,
  },
  {
    id: 'prog-3',
    nama: 'Digitalisasi Database KTA & Portal Informasi Pasirwangi',
    deskripsi: 'Pembaruan data anggota berbasis sistem daring, integrasi KTA digital, dan penyediaan media informasi transparan untuk kemudahan pelayanan organisasi.',
    bidang: 'Kominfo & Digital',
    target: '548+ Anggota Terdata',
    waktuPelaksanaan: 'Januari - April 2026',
    tahun: '2026',
    status: 'Selesai',
    penanggungJawab: 'Yayan Hendrayana, M.Kom.',
    progressPercent: 100,
  },
  {
    id: 'prog-4',
    nama: 'Pekan Olahraga & Seni Guru (PORSENI) Pasirwangi 2026',
    deskripsi: 'Ajang silaturahmi olahraga voli, bulu tangkis, tenis meja, dan seni tarik suara antar-ranting sekolah dalam rangka memupuk solidaritas anggota.',
    bidang: 'Seni & Olahraga',
    target: '12 Ranting Sekolah se-Kecamatan',
    waktuPelaksanaan: 'Agustus 2026',
    tahun: '2026',
    status: 'Direncanakan',
    penanggungJawab: 'Endang Sutisna, S.Pd.Jas.',
    progressPercent: 25,
  },
  {
    id: 'prog-5',
    nama: 'Program Dana Sosial & Santunan Guru Purna Bakti / Duka',
    deskripsi: 'Pemberian apresiasi cinderamata bagi guru yang memasuki masa purna tugas dan santunan kesetiakawanan bagi keluarga anggota yang tertimpa musibah.',
    bidang: 'Kesejahteraan',
    target: 'Seluruh Anggota Terkena Musibah / Purna Tugas',
    waktuPelaksanaan: 'Sepanjang Tahun',
    tahun: '2026',
    status: 'Sedang Berjalan',
    penanggungJawab: 'Rina Marlina, S.Pd.',
    progressPercent: 50,
  },
  {
    id: 'prog-6',
    nama: 'Peringatan Hari Guru Nasional (HGN) & HUT PGRI ke-81',
    deskripsi: 'Upacara akbar, bakti sosial pendidikan ke desa terpencil, seminar nasional pendidikan, dan penganugerahan Guru Inspiratif Pasirwangi.',
    bidang: 'Pimpinan & Sekretariat',
    target: 'Seluruh Pendidik & Tenaga Kependidikan',
    waktuPelaksanaan: 'November 2026',
    tahun: '2026',
    status: 'Direncanakan',
    penanggungJawab: 'Cecep Kurnia, S.Pd., M.Si.',
    progressPercent: 10,
  },
];

export const initialKegiatan: KegiatanItem[] = [
  {
    id: 'keg-1',
    nama: 'Pelatihan Literasi Digital & Penguatan Kurikulum Merdeka Guru Pasirwangi',
    tanggal: '15 Februari 2026',
    waktu: '08:00 - 15:30 WIB',
    lokasi: 'Aula SMPN 1 Pasirwangi, Garut',
    deskripsi: 'Kegiatan kolaboratif peningkatan kompetensi merancang modul ajar berbasis proyek kontekstual lingkungan pertanian dan panas bumi Kamojang.',
    pesertaCount: 145,
    fotoUtama: '/images/hero_pgri.jpg',
    galeriDokumentasi: [
      '/images/hero_pgri.jpg',
      '/images/ketua_pgri.jpg',
    ],
  },
  {
    id: 'keg-2',
    nama: 'Konferensi Kerja Cabang (KONKERCAB) I PGRI Pasirwangi',
    tanggal: '10 Januari 2026',
    waktu: '08:30 - 16:00 WIB',
    lokasi: 'Gedung KPRI Guru Pasirwangi',
    deskripsi: 'Evaluasi program kerja tahunan serta penetapan agenda strategis dan pengesahan rencana anggaran tahun 2026 bersama seluruh perwakilan pengurus ranting.',
    pesertaCount: 85,
    fotoUtama: '/images/hero_pgri.jpg',
    galeriDokumentasi: [
      '/images/hero_pgri.jpg',
    ],
  },
  {
    id: 'keg-3',
    nama: 'Senam Bersama & Jalan Sehat Guru Se-Kecamatan Pasirwangi',
    tanggal: '22 November 2025',
    waktu: '06:30 - 11:00 WIB',
    lokasi: 'Lapangan Sepak Bola Pasirwangi',
    deskripsi: 'Semarak Hari Guru Nasional dengan aksi jalan sehat menyusuri panorama bukit Pasirwangi, diiringi pembagian ratusan doorprize pendidikan.',
    pesertaCount: 380,
    fotoUtama: '/images/hero_pgri.jpg',
    galeriDokumentasi: [
      '/images/hero_pgri.jpg',
    ],
  },
];

export const initialBerita: BeritaItem[] = [
  {
    id: 'ber-1',
    slug: 'peluncuran-portal-informasi-digital-pgri-pasirwangi-2026',
    judul: 'PGRI Pasirwangi Resmi Luncurkan Portal Informasi Digital untuk Tingkatkan Pelayanan Guru',
    ringkasan: 'Sebagai langkah mewujudkan transparansi dan pelayanan cepat bagi pendidik, PGRI Cabang Pasirwangi kini memiliki wadah informasi dan pendaftaran online mandiri.',
    isi: `Pasirwangi, Garut — Dalam rangka menyongsong era keterbukaan informasi dan mempermudah akses pelayanan bagi seluruh tenaga pendidik, Pengurus PGRI Cabang Kecamatan Pasirwangi secara resmi meluncurkan Portal Informasi Digital Organisasi pada awal tahun 2026.

Ketua PGRI Cabang Pasirwangi, H. Ahmad Sobari, S.Pd., M.M.Pd., menyatakan bahwa inovasi portal ini adalah jawaban atas kebutuhan guru di era modern. "Sekarang bapak dan ibu guru di seluruh penjuru Pasirwangi tidak perlu menempuh perjalanan jauh hanya untuk mengurus verifikasi anggota, konsultasi perlindungan profesi, atau menyampaikan aspirasi. Semua layanan dapat diakses hanya dalam genggaman melalui ponsel cerdas," tuturnya.

Portal ini dilengkapi fitur pendaftaran anggota baru, tracking aspirasi, kalender agenda resmi, dokumentasi kegiatan, galeri video edukasi, hingga ruang bimbingan karya tulis. Dengan semangat gotong royong, seluruh pengurus ranting menyambut antusias kehadiran inovasi digital ini sebagai role model kepengurusan cabang di Kabupaten Garut.`,
    kategori: 'Organisasi',
    tanggal: '2026-03-20',
    penulis: 'Bidang Publikasi & Media PGRI',
    fotoUrl: '/images/hero_pgri.jpg',
    dibacaCount: 384,
    featured: true,
  },
  {
    id: 'ber-2',
    slug: 'sosialisasi-perlindungan-hukum-guru-pasirwangi-cegah-kriminalisasi',
    judul: 'Cegah Kriminalisasi Pendidik, PGRI Pasirwangi Gelar Penyuluhan Hukum Bersama Pakar',
    ringkasan: 'Bidang Advokasi memberikan edukasi komprehensif terkait batasan disiplin kelas dan perlindungan profesi guru dalam bertugas mendidik siswa.',
    isi: `Pasirwangi — Demi memberi rasa aman dan kepastian hukum bagi para pendidik saat menjalankan kewajiban mendisiplinkan dan membina peserta didik, Bidang Advokasi & Perlindungan Hukum PGRI Pasirwangi menggelar sosialisasi hukum bertajuk "Mendidik Tanpa Rasa Takut: Memahami Payung Hukum Profesi Guru".

Kegiatan ini menghadirkan praktisi hukum dan pembina dinas pendidikan yang mengupas tuntas UU No. 14 Tahun 2005 serta Peraturan Mendikbud No. 10 Tahun 2017 tentang Perlindungan bagi Pendidik. Ketua Bidang Advokasi menegaskan bahwa PGRI Pasirwangi berdiri kokoh di garda terdepan mengawal guru yang bertindak sesuai kode etik profesi.`,
    kategori: 'Pendidikan',
    tanggal: '2026-02-28',
    penulis: 'Asep Saepuloh, S.H.',
    fotoUrl: '/images/hero_pgri.jpg',
    dibacaCount: 295,
  },
  {
    id: 'ber-3',
    slug: 'guru-pasirwangi-raih-penghargaan-inovasi-pembelajaran-sains-kabupaten',
    judul: 'Membanggakan! Guru SDN 1 Pasirwangi Sabet Juara Inovasi Media Ajar Tingkat Kabupaten Garut',
    ringkasan: 'Karya media ajar interaktif pemanfaatan energi terbarukan panas bumi Kamojang berhasil memukau dewan juri lomba inovasi guru.',
    isi: `Garut — Prestasi gemilang kembali ditorehkan oleh anggota PGRI Cabang Kecamatan Pasirwangi. Ibu Nenden Ratnasari, S.Pd., guru kelas SDN 1 Pasirwangi, sukses meraih Juara I Lomba Inovasi Pembelajaran Berdiferensiasi Tingkat Kabupaten Garut.

Media yang dikembangkan memanfaatkan studi kasus langsung kearifan lokal PLTP Kamojang dan pertanian kentang dataran tinggi Pasirwangi dalam pembelajaran IPA tematik, sehingga siswa dapat memahami konsep sains secara nyata dan menyenangkan. PGRI Pasirwangi menyampaikan apresiasi setinggi-tingginya dan piagam penghargaan khusus kepada beliau.`,
    kategori: 'Prestasi',
    tanggal: '2026-01-18',
    penulis: 'Humas PGRI Pasirwangi',
    fotoUrl: '/images/hero_pgri.jpg',
    dibacaCount: 421,
  },
  {
    id: 'ber-4',
    slug: 'pengumuman-verifikasi-kta-digital-pgri-2026',
    judul: 'Pengumuman Penting: Pemutakhiran Data Anggota & Cetak KTA Digital PGRI Pasirwangi',
    ringkasan: 'Dihimbau kepada seluruh anggota baik ASN, PPPK, maupun Non-ASN untuk memperbarui data nomor anggota dan sekolah pangkalan.',
    isi: `Diumumkan kepada seluruh Pengurus Ranting dan Anggota PGRI se-Kecamatan Pasirwangi bahwa Sekretariat Cabang membuka layanan pemutakhiran data keanggotaan untuk penerbitan Kartu Tanda Anggota (KTA) Digital terintegrasi nasional.

Proses pembaruan data dapat dilakukan secara mandiri melalui menu "Pendaftaran PGRI" pada portal resmi ini atau dikoordinasikan langsung melalui ketua ranting sekolah masing-masing. Pelayanan ini tidak dipungut biaya dan berlaku hingga batas waktu akhir semester genap 2026.`,
    kategori: 'Pengumuman',
    tanggal: '2026-03-05',
    penulis: 'Sekretariat PGRI Cabang',
    fotoUrl: '/images/hero_pgri.jpg',
    dibacaCount: 512,
  },
];

export const initialPrestasi: PrestasiItem[] = [
  {
    id: 'pres-1',
    namaPrestasi: 'Juara I Lomba Inovasi Pembelajaran Berdiferensiasi',
    tahun: '2026',
    penerima: 'Nenden Ratnasari, S.Pd. (SDN Pasirwangi 1)',
    kategori: 'Guru',
    tingkat: 'Kabupaten',
    fotoPiagam: '/images/hero_pgri.jpg',
    deskripsi: 'Keberhasilan menciptakan media pembelajaran interaktif berbasis fenomena geotermal Kamojang bagi murid sekolah dasar.',
  },
  {
    id: 'pres-2',
    namaPrestasi: 'Juara II Turnamen Bola Voli Guru PGRI Cup',
    tahun: '2025',
    penerima: 'Tim Voli Putra PGRI Cabang Pasirwangi',
    kategori: 'Organisasi',
    tingkat: 'Kabupaten',
    fotoPiagam: '/images/hero_pgri.jpg',
    deskripsi: 'Prestasi gemilang tim olahraga guru Pasirwangi dalam ajang pekan olahraga antar-cabang se-Kabupaten Garut.',
  },
  {
    id: 'pres-3',
    namaPrestasi: 'Juara Harapan I Guru Berprestasi dan Berdedikasi Jenjang SMP',
    tahun: '2024',
    penerima: 'Drs. H. Maman Suratman (SMPN 1 Pasirwangi)',
    kategori: 'Guru',
    tingkat: 'Provinsi',
    fotoPiagam: '/images/hero_pgri.jpg',
    deskripsi: 'Dedikasi lebih dari 30 tahun mengabdi di daerah perbukitan dan memajukan literasi numerasi di Pasirwangi.',
  },
  {
    id: 'pres-4',
    namaPrestasi: 'Penghargaan Cabang PGRI Teraktif dalam Program Perlindungan Profesi Guru',
    tahun: '2025',
    penerima: 'PGRI Cabang Kecamatan Pasirwangi',
    kategori: 'Organisasi',
    tingkat: 'Kabupaten',
    fotoPiagam: '/images/hero_pgri.jpg',
    deskripsi: 'Dianugerahkan oleh Pengurus PGRI Kabupaten Garut atas kecepatan respon dan kepedulian advokasi terhadap para pendidik.',
  },
];

export const initialGaleri: GaleriItem[] = [
  {
    id: 'gal-1',
    tipe: 'foto',
    judul: 'Upacara Peringatan Hari Guru Nasional di Pasirwangi',
    deskripsi: 'Ratusan guru dengan khidmat mengenakan seragam batik PGRI Kusuma Bangsa di pelataran kantor kecamatan.',
    url: '/images/hero_pgri.jpg',
    kategori: 'Upacara & Peringatan',
    tahun: '2025',
  },
  {
    id: 'gal-2',
    tipe: 'foto',
    judul: 'Musyawarah Kerja Cabang Bersama Para Ketua Ranting',
    deskripsi: 'Diskusi pemantapan program kerja tahunan demi kesejahteraan anggota dan mutu pendidikan.',
    url: '/images/hero_pgri.jpg',
    kategori: 'Rapat Organisasi',
    tahun: '2026',
  },
  {
    id: 'gal-3',
    tipe: 'foto',
    judul: 'Bakti Sosial & Santunan Pendidikan Anak Yatim Pasirwangi',
    deskripsi: 'Aksi peduli solidaritas guru PGRI memberikan bantuan beasiswa alat tulis dan pakaian sekolah.',
    url: '/images/hero_pgri.jpg',
    kategori: 'Sosial & Solidaritas',
    tahun: '2025',
  },
  {
    id: 'gal-4',
    tipe: 'video',
    judul: 'Profil Singkat PGRI Cabang Pasirwangi & Semangat Dedikasi Guru',
    deskripsi: 'Tayangan video dokumenter mengenai perjuangan para pahlawan tanpa tanda jasa di Kecamatan Pasirwangi Garut.',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnailUrl: '/images/hero_pgri.jpg',
    kategori: 'Profil Video',
    tahun: '2026',
  },
  {
    id: 'gal-5',
    tipe: 'video',
    judul: 'Hymne & Mars PGRI Berkumandang di Pelosok Garut Selatan',
    deskripsi: 'Paduan suara guru PGRI Pasirwangi menyanyikan lagu kebanggaan organisasi.',
    url: 'https://www.youtube.com/watch?v=3JZ_D3ELwOQ',
    youtubeId: '3JZ_D3ELwOQ',
    thumbnailUrl: '/images/hero_pgri.jpg',
    kategori: 'Kesenian',
    tahun: '2025',
  },
];

export const initialKalender: KalenderItem[] = [
  {
    id: 'kal-1',
    judul: 'Rapat Koordinasi Bulanan Pengurus Cabang & Ranting',
    tanggal: '2026-04-08',
    jamMulai: '09:00',
    jamSelesai: '12:00',
    lokasi: 'Sekretariat PGRI Pasirwangi, Jl. Raya Pasirwangi No. 12',
    penanggungJawab: 'Cecep Kurnia, S.Pd., M.Si.',
    deskripsi: 'Pembahasan progres pendaftaran KTA digital baru dan evaluasi persiapan PORSENI 2026.',
    kategori: 'Rapat',
    status: 'Akan Datang',
  },
  {
    id: 'kal-2',
    judul: 'Workshop Penulisan Karya Ilmiah Guru & PTK',
    tanggal: '2026-04-18',
    jamMulai: '08:30',
    jamSelesai: '15:00',
    lokasi: 'Laboratorium Komputer SMPN 1 Pasirwangi',
    penanggungJawab: 'Siti Maryam, S.Pd., M.Pd.',
    deskripsi: 'Bimbingan teknis menyusun Penelitian Tindakan Kelas (PTK) untuk kenaikan pangkat ASN/PPPK.',
    kategori: 'Pelatihan',
    status: 'Akan Datang',
  },
  {
    id: 'kal-3',
    judul: 'Peringatan Hari Pendidikan Nasional (HARDIKNAS) 2026',
    tanggal: '2026-05-02',
    jamMulai: '07:30',
    jamSelesai: '10:30',
    lokasi: 'Halaman Kantor Kecamatan Pasirwangi',
    penanggungJawab: 'H. Ahmad Sobari, S.Pd.',
    deskripsi: 'Upacara bendera gabungan seluruh instansi pendidikan dan guru se-Kecamatan Pasirwangi.',
    kategori: 'Upacara',
    status: 'Akan Datang',
  },
  {
    id: 'kal-4',
    judul: 'Seleksi Atlet Guru Pasirwangi Cabang Bulu Tangkis & Tenis Meja',
    tanggal: '2026-05-20',
    jamMulai: '13:30',
    jamSelesai: '17:00',
    lokasi: 'GOR Barusari Pasirwangi',
    penanggungJawab: 'Endang Sutisna, S.Pd.Jas.',
    deskripsi: 'Penjaringan bakat atlet olahraga antar guru ranting untuk kontingen Kabupaten.',
    kategori: 'Lomba',
    status: 'Akan Datang',
  },
];

export const initialLayanan: LayananItem[] = [
  {
    id: 'lay-1',
    nama: 'Pendaftaran Anggota Baru & Pembuatan KTA Digital',
    deskripsi: 'Layanan registrasi keanggotaan PGRI resmi bagi Guru PNS, PPPK, Guru Tetap Yayasan, dan Guru Honorer sekolah.',
    syarat: [
      'Memiliki NIK & NUPTK / PegID valid',
      'Surat keterangan aktif mengajar dari kepala sekolah',
      'Foto diri resmi (latar belakang merah/putih)',
    ],
    ikon: 'Users',
    kontakPic: 'Cecep Kurnia (Sekretaris)',
    estimasiHari: '1 - 3 Hari Kerja',
  },
  {
    id: 'lay-2',
    nama: 'Pembaruan & Mutasi Data Keanggotaan',
    deskripsi: 'Layanan perubahan pangkalan sekolah, perubahan status kepegawaian (misal dari Honorer ke PPPK), atau perubahan gelar.',
    syarat: [
      'Nomor KTA lama / nomor registrasi',
      'SK mutasi atau SK pengangkatan terbaru',
      'Kartu Identitas KTP',
    ],
    ikon: 'FileText',
    kontakPic: 'Irma Suryani (Wk. Sekretaris)',
    estimasiHari: '1 - 2 Hari Kerja',
  },
  {
    id: 'lay-3',
    nama: 'Konsultasi Advokasi & Bantuan Hukum Profesi Guru',
    deskripsi: 'Bantuan konsultasi hukum cuma-cuma dan pendampingan mediasi bila menghadapi permasalahan hukum terkait tugas profesi.',
    syarat: [
      'Anggota resmi PGRI Pasirwangi aktif',
      'Kronologi tertulis permasalahan',
      'Dokumen pendukung terkait',
    ],
    ikon: 'Shield',
    kontakPic: 'Asep Saepuloh, S.H. (Bidang Advokasi)',
    estimasiHari: 'Respon Cepat 24 Jam',
  },
  {
    id: 'lay-4',
    nama: 'Permohonan Narasumber & Rekomendasi Pelatihan',
    deskripsi: 'Fasilitasi narasumber ahli Kurikulum Merdeka, karya tulis ilmiah, dan penguji kompetensi bagi gugus KKG/MGMP di Pasirwangi.',
    syarat: [
      'Surat permohonan dari gugus/ranting/sekolah',
      'Jadwal dan rincian topik materi',
    ],
    ikon: 'BookOpen',
    kontakPic: 'Siti Maryam (Bidang Profesi)',
    estimasiHari: '2 - 4 Hari Kerja',
  },
  {
    id: 'lay-5',
    nama: 'Pengajuan Dana Sosial & Santunan Kesetiakawanan',
    deskripsi: 'Penyaluran santunan duka anggota, santunan musibah/bencana, dan tanda kasih purna tugas guru.',
    syarat: [
      'Surat pengantar dari Ketua Ranting',
      'Fotokopi KTA & KTP pemohon',
      'Keterangan purna tugas atau surat kematian',
    ],
    ikon: 'HeartHandshake',
    kontakPic: 'Rina Marlina (Bidang Kesejahteraan)',
    estimasiHari: '2 - 3 Hari Kerja',
  },
  {
    id: 'lay-6',
    nama: 'Kanal Pengaduan & Aspirasi Anggota Pendidik',
    deskripsi: 'Saluran resmi penyampaian aspirasi, saran kebijakan pendidikan, maupun uneg-uneg guru secara transparan dan terpantau.',
    syarat: [
      'Dapat diajukan secara terbuka maupun anonim',
      'Uraian masalah yang jelas dan bertanggung jawab',
    ],
    ikon: 'MessageSquare',
    kontakPic: 'Pengurus Harian Cabang',
    estimasiHari: 'Respon Maks. 2x24 Jam',
  },
];

export const initialPendaftaran: PendaftaranItem[] = [
  {
    id: 'reg-demo-1',
    nomorPendaftaran: 'REG-2026-0041',
    tanggalDaftar: '2026-03-24',
    namaLengkap: 'Rudi Hartono, S.Pd.',
    nikNip: '3205121405920003',
    nuptk: '4567768669100023',
    tempatTanggalLahir: 'Garut, 14 Mei 1992',
    jenisKelamin: 'Laki-laki',
    instansi: 'SDN Barusari 1',
    jabatan: 'Guru Kelas V',
    mapel: 'Tematik Sekolah Dasar',
    alamat: 'Kp. Barusari RT 02 RW 04 Desa Barusari, Pasirwangi',
    noWhatsApp: '081234567890',
    email: 'rudihartono.edu@gmail.com',
    kecamatan: 'Pasirwangi',
    statusKepegawaian: 'PPPK',
    status: 'Diterima',
    catatanAdmin: 'Data lengkap, KTA Digital telah diterbitkan dengan No. Anggota: 3205.12.0489.',
  },
  {
    id: 'reg-demo-2',
    nomorPendaftaran: 'REG-2026-0042',
    tanggalDaftar: '2026-03-26',
    namaLengkap: 'Dewi Lestari, S.Pd.I.',
    nikNip: '3205126809950001',
    nuptk: '8901770671300054',
    tempatTanggalLahir: 'Garut, 28 September 1995',
    jenisKelamin: 'Perempuan',
    instansi: 'SMPN 2 Pasirwangi',
    jabatan: 'Guru Mata Pelajaran',
    mapel: 'Pendidikan Agama Islam',
    alamat: 'Kp. Pasirwangi Kolot RT 01 RW 01 Desa Pasirwangi',
    noWhatsApp: '085721123456',
    email: 'dewilestari.pai@gmail.com',
    kecamatan: 'Pasirwangi',
    statusKepegawaian: 'Guru Tetap Yayasan',
    status: 'Diverifikasi',
    catatanAdmin: 'Dokumen sedang dalam pengecekan berkas keaktifan pangkalan dapodik.',
  },
];

export const initialAspirasi: AspirasiItem[] = [
  {
    id: 'asp-demo-1',
    tiketId: 'ASP-2026-0001',
    tanggal: '2026-03-22',
    nama: 'Anonim (Guru Honorer Pasirwangi)',
    isAnonim: true,
    noWhatsApp: '081399887766',
    instansi: 'Ranting SD Wilayah Utara',
    kategori: 'Kesejahteraan',
    judul: 'Usulan Advokasi Penambahan Formasi PPPK Guru Kelas di Kecamatan Pasirwangi',
    isi: 'Mohon kepada Pengurus PGRI Pasirwangi untuk memperjuangkan aspirasi kami guru honorer yang telah mengabdi lebih dari 8 tahun agar formasi PPPK guru kelas sekolah dasar di Pasirwangi ditambah pada seleksi tahun ini.',
    status: 'Diproses',
    responAdmin: 'Aspirasi telah diagendakan untuk disampaikan dalam audiensi bersama PGRI Kabupaten Garut dan BKPSDM Garut pada awal bulan mendatang. Terima kasih atas masukan rekan guru.',
    tanggalRespon: '2026-03-25',
  },
  {
    id: 'asp-demo-2',
    tiketId: 'ASP-2026-0002',
    tanggal: '2026-03-25',
    nama: 'Budi Santoso, S.Pd.',
    isAnonim: false,
    noWhatsApp: '082123445566',
    instansi: 'SDN Sarimukti 2',
    kategori: 'Sarana dan Prasarana',
    judul: 'Usulan Pengadaan Pelatihan Pembuatan Media Digital Interaktif di Wilayah Desa Sarimukti',
    isi: 'Kami di gugus sekolah perbukitan berharap ada tim fasilitator PGRI yang turun langsung mengadakan workshop offline pembuatan modul canva dan video pembelajaran.',
    status: 'Selesai',
    responAdmin: 'Usulan disetujui. Tim Litbang PGRI Pasirwangi menjadwalkan workshop zona timur pada bulan Mei 2026 bertempat di SDN Sarimukti 1.',
    tanggalRespon: '2026-03-27',
  },
];

export const initialSocialMedia: SocialMediaLinks = {
  facebook: 'https://facebook.com/pgripasirwangi',
  instagram: 'https://instagram.com/pgri_pasirwangi',
  youtube: 'https://youtube.com/@pgricabangpasirwangi',
  tiktok: 'https://tiktok.com/@pgripasirwangi',
  whatsapp: 'https://wa.me/6281223456789',
  telegram: 'https://t.me/pgripasirwangi',
  website: 'https://pgri-pasirwangi.or.id',
};

export const initialSiteSettings: SiteSettings = {
  portalTitle: 'PORTAL INFORMASI PGRI KECAMATAN PASIRWANGI',
  tagline: 'Bersama Guru, Membangun Pendidikan, Menguatkan Organisasi',
  deskripsiHero:
    'Media informasi digital PGRI Cabang Kecamatan Pasirwangi yang menyajikan informasi organisasi, program kerja, kegiatan, layanan anggota, berita, dokumentasi, dan berbagai informasi pendidikan.',
  pengumumanDarurat: 'Pelayanan KTA Digital Baru dan Verifikasi Data Keanggotaan Masa Bakti 2025-2030 kini dibuka daring!',
  logoAplikasiUrl: '',
  logoTitleUrl: '',
  visitorStats: {
    hariIni: 148,
    bulanIni: 4210,
    total: 31250,
  },
};
